apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z19b7frcu-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-965655582e.c7mj.p3.openshiftapps.com/rhtap/rhtap-qe-python:87986a4de43ec25720ae62b3dcffe25ad7d4c55e@sha256:60c70aec2e9a8750004cb6c7f0611574bccb5ba1afb9122a7693d84b918c162b
          name: container-image
