apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z19b7frcu-python
  janus-idp.io/tekton: z19b7frcu-python
  backstage.io/kubernetes-id: z19b7frcu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z19b7frcu-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
